apiVersion: v1
kind: Secret
metadata:
    name: udagram-aws
stringData:
    credentials: |
        [default]
        aws_access_key_id = <enter>
        aws_secret_access_key = <enter>
        aws_session_token = <enter>